os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
"".increment STEXT nosplit size=13 args=0x8 locals=0x0
	0x0000 00000 (gorace.go:9)	TEXT	"".increment(SB), NOSPLIT|ABIInternal, $0-8
	0x0000 00000 (gorace.go:9)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (gorace.go:9)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (gorace.go:9)	FUNCDATA	$2, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (gorace.go:10)	PCDATA	$0, $0
	0x0000 00000 (gorace.go:10)	PCDATA	$1, $0
	0x0000 00000 (gorace.go:10)	MOVQ	"".amt+8(SP), AX
	0x0005 00005 (gorace.go:10)	ADDQ	AX, "".counter(SB)
	0x000c 00012 (gorace.go:11)	RET
	0x0000 48 8b 44 24 08 48 01 05 00 00 00 00 c3           H.D$.H.......
	rel 8+4 t=15 "".counter+0
"".main STEXT size=221 args=0x0 locals=0x58
	0x0000 00000 (gorace.go:13)	TEXT	"".main(SB), ABIInternal, $88-0
	0x0000 00000 (gorace.go:13)	MOVQ	(TLS), CX
	0x0009 00009 (gorace.go:13)	CMPQ	SP, 16(CX)
	0x000d 00013 (gorace.go:13)	JLS	211
	0x0013 00019 (gorace.go:13)	SUBQ	$88, SP
	0x0017 00023 (gorace.go:13)	MOVQ	BP, 80(SP)
	0x001c 00028 (gorace.go:13)	LEAQ	80(SP), BP
	0x0021 00033 (gorace.go:13)	FUNCDATA	$0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0021 00033 (gorace.go:13)	FUNCDATA	$1, gclocals·568470801006e5c0dc3947ea998fe279(SB)
	0x0021 00033 (gorace.go:13)	FUNCDATA	$2, gclocals·bfec7e55b3f043d1941c093912808913(SB)
	0x0021 00033 (gorace.go:13)	FUNCDATA	$3, "".main.stkobj(SB)
	0x0021 00033 (gorace.go:14)	PCDATA	$0, $0
	0x0021 00033 (gorace.go:14)	PCDATA	$1, $0
	0x0021 00033 (gorace.go:14)	MOVL	$8, (SP)
	0x0028 00040 (gorace.go:14)	PCDATA	$0, $1
	0x0028 00040 (gorace.go:14)	LEAQ	"".increment·f(SB), AX
	0x002f 00047 (gorace.go:14)	PCDATA	$0, $0
	0x002f 00047 (gorace.go:14)	MOVQ	AX, 8(SP)
	0x0034 00052 (gorace.go:14)	MOVQ	$5, 16(SP)
	0x003d 00061 (gorace.go:14)	CALL	runtime.newproc(SB)
	0x0042 00066 (gorace.go:15)	MOVL	$8, (SP)
	0x0049 00073 (gorace.go:15)	PCDATA	$0, $1
	0x0049 00073 (gorace.go:15)	LEAQ	"".increment·f(SB), AX
	0x0050 00080 (gorace.go:15)	PCDATA	$0, $0
	0x0050 00080 (gorace.go:15)	MOVQ	AX, 8(SP)
	0x0055 00085 (gorace.go:15)	MOVQ	$10, 16(SP)
	0x005e 00094 (gorace.go:15)	CALL	runtime.newproc(SB)
	0x0063 00099 (gorace.go:17)	MOVQ	"".counter(SB), AX
	0x006a 00106 (gorace.go:17)	MOVQ	AX, (SP)
	0x006e 00110 (gorace.go:17)	CALL	runtime.convT64(SB)
	0x0073 00115 (gorace.go:17)	PCDATA	$0, $1
	0x0073 00115 (gorace.go:17)	MOVQ	8(SP), AX
	0x0078 00120 (gorace.go:17)	PCDATA	$1, $1
	0x0078 00120 (gorace.go:17)	XORPS	X0, X0
	0x007b 00123 (gorace.go:17)	MOVUPS	X0, ""..autotmp_12+64(SP)
	0x0080 00128 (gorace.go:17)	PCDATA	$0, $2
	0x0080 00128 (gorace.go:17)	LEAQ	type.int(SB), CX
	0x0087 00135 (gorace.go:17)	PCDATA	$0, $1
	0x0087 00135 (gorace.go:17)	MOVQ	CX, ""..autotmp_12+64(SP)
	0x008c 00140 (gorace.go:17)	PCDATA	$0, $0
	0x008c 00140 (gorace.go:17)	MOVQ	AX, ""..autotmp_12+72(SP)
	0x0091 00145 (<unknown line number>)	NOP
	0x0091 00145 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0091 00145 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0098 00152 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $2
	0x0098 00152 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x009f 00159 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x009f 00159 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x00a3 00163 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00a3 00163 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x00a8 00168 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00a8 00168 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $0
	0x00a8 00168 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_12+64(SP), AX
	0x00ad 00173 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00ad 00173 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x00b2 00178 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x00bb 00187 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x00c4 00196 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x00c9 00201 (<unknown line number>)	MOVQ	80(SP), BP
	0x00ce 00206 (<unknown line number>)	ADDQ	$88, SP
	0x00d2 00210 (<unknown line number>)	RET
	0x00d3 00211 (<unknown line number>)	NOP
	0x00d3 00211 (gorace.go:13)	PCDATA	$1, $-1
	0x00d3 00211 (gorace.go:13)	PCDATA	$0, $-1
	0x00d3 00211 (gorace.go:13)	CALL	runtime.morestack_noctxt(SB)
	0x00d8 00216 (gorace.go:13)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 c0  eH..%....H;a....
	0x0010 00 00 00 48 83 ec 58 48 89 6c 24 50 48 8d 6c 24  ...H..XH.l$PH.l$
	0x0020 50 c7 04 24 08 00 00 00 48 8d 05 00 00 00 00 48  P..$....H......H
	0x0030 89 44 24 08 48 c7 44 24 10 05 00 00 00 e8 00 00  .D$.H.D$........
	0x0040 00 00 c7 04 24 08 00 00 00 48 8d 05 00 00 00 00  ....$....H......
	0x0050 48 89 44 24 08 48 c7 44 24 10 0a 00 00 00 e8 00  H.D$.H.D$.......
	0x0060 00 00 00 48 8b 05 00 00 00 00 48 89 04 24 e8 00  ...H......H..$..
	0x0070 00 00 00 48 8b 44 24 08 0f 57 c0 0f 11 44 24 40  ...H.D$..W...D$@
	0x0080 48 8d 0d 00 00 00 00 48 89 4c 24 40 48 89 44 24  H......H.L$@H.D$
	0x0090 48 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48  HH......H......H
	0x00a0 89 0c 24 48 89 44 24 08 48 8d 44 24 40 48 89 44  ..$H.D$.H.D$@H.D
	0x00b0 24 10 48 c7 44 24 18 01 00 00 00 48 c7 44 24 20  $.H.D$.....H.D$ 
	0x00c0 01 00 00 00 e8 00 00 00 00 48 8b 6c 24 50 48 83  .........H.l$PH.
	0x00d0 c4 58 c3 e8 00 00 00 00 e9 23 ff ff ff           .X.......#...
	rel 5+4 t=16 TLS+0
	rel 43+4 t=15 "".increment·f+0
	rel 62+4 t=8 runtime.newproc+0
	rel 76+4 t=15 "".increment·f+0
	rel 95+4 t=8 runtime.newproc+0
	rel 102+4 t=15 "".counter+0
	rel 111+4 t=8 runtime.convT64+0
	rel 131+4 t=15 type.int+0
	rel 148+4 t=15 os.Stdout+0
	rel 155+4 t=15 go.itab.*os.File,io.Writer+0
	rel 197+4 t=8 fmt.Fprintln+0
	rel 212+4 t=8 runtime.morestack_noctxt+0
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 19+4 t=28 go.info.[]interface {}+0
	rel 27+4 t=28 go.info.int+0
	rel 37+4 t=28 go.info.error+0
go.loc.os.(*File).close SDWARFLOC dupok size=0
go.info.os.(*File).close SDWARFINFO dupok size=55
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 63 6c 6f 73  .os.(*File).clos
	0x0010 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  e...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 ec  ..........~r0...
	0x0030 01 00 00 00 00 00 00                             .......
	rel 18+8 t=1 os.(*File).close+0
	rel 26+8 t=1 os.(*File).close+26
	rel 36+4 t=29 gofile..<autogenerated>+0
	rel 49+4 t=28 go.info.error+0
go.range.os.(*File).close SDWARFRANGE dupok size=0
go.isstmt.os.(*File).close SDWARFMISC dupok size=0
	0x0000 04 05 01 10 02 05 00                             .......
go.loc."".increment SDWARFLOC size=35
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 01 00 9c 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0020 00 00 00                                         ...
	rel 0+8 t=50 "".increment+0
	rel 8+8 t=50 "".increment+13
go.info."".increment SDWARFINFO size=53
	0x0000 03 22 22 2e 69 6e 63 72 65 6d 65 6e 74 00 00 00  ."".increment...
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 9c  ................
	0x0020 00 00 00 00 01 10 61 6d 74 00 00 09 00 00 00 00  ......amt.......
	0x0030 00 00 00 00 00                                   .....
	rel 14+8 t=1 "".increment+0
	rel 22+8 t=1 "".increment+13
	rel 32+4 t=29 gofile../Users/androo/Documents/playground/playground/go/asm/gorace.go+0
	rel 44+4 t=28 go.info.int+0
	rel 48+4 t=28 go.loc."".increment+0
go.range."".increment SDWARFRANGE size=0
go.isstmt."".increment SDWARFMISC size=0
	0x0000 04 05 01 07 02 01 00                             .......
go.loc."".main SDWARFLOC size=0
go.info."".main SDWARFINFO size=63
	0x0000 03 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 11 00 00 00 00 00     ...............
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+221
	rel 27+4 t=29 gofile../Users/androo/Documents/playground/playground/go/asm/gorace.go+0
	rel 33+4 t=28 go.info.fmt.Println$abstract+0
	rel 37+8 t=1 "".main+145
	rel 45+8 t=1 "".main+201
	rel 53+4 t=29 gofile../Users/androo/Documents/playground/playground/go/asm/gorace.go+0
go.range."".main SDWARFRANGE size=0
go.isstmt."".main SDWARFMISC size=0
	0x0000 04 13 04 0e 03 07 01 15 02 0c 01 15 02 0c 01 04  ................
	0x0010 02 05 01 1e 02 07 01 2c 02 05 01 0a 02 0a 00     .......,.......
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 00 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 00 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 00 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
"".counter SNOPTRBSS size=8
"".increment·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 "".increment+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·568470801006e5c0dc3947ea998fe279 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 00 02                    ..........
gclocals·bfec7e55b3f043d1941c093912808913 SRODATA dupok size=11
	0x0000 03 00 00 00 02 00 00 00 00 01 03                 ...........
"".main.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
